baseURL = "https://ljs.dev"
languageCode = "en-us"
title = "Leon Stafford"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
