account_id = "7d863571a303c5eddc8d4c48b66bef8d"
name = "workers-www-ljsdotdev"
type = "webpack"
route = "ljs.dev/*"
workers_dev = false
zone_id = "88df208cedb95208a6ca56e32c77176e"

[site]
bucket = "public"
entry-point = "workers-site"
